image:
  file: .gitpod.Dockerfile

checkoutLocation: "go/src/github.com/bambruysk/wildberry_go"
workspaceLocation: "go/src/github.com/bambruysk/wildberry_go"

tasks:
  - init: dep ensure >
      go build -o app
    command: >
      ./app

vscode:
  extensions:
    - premparihar.gotestexplorer@0.1.10:jvUM8akrQ67vQxfjaxCgCg==